[project]
name = "backtest-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cvxpy>=1.7.3",
    "numpy>=2.3.4",
    "polars>=1.35.1",
    "sf-quant>=0.1.14",
]
